# Generated by Django 3.2.9 on 2022-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_h1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealttext',
            name='text',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
